/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  PlagiarismAlgorithm as PrismaPlagiarismAlgorithm,
} from "@prisma/client";

export class PlagiarismAlgorithmServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PlagiarismAlgorithmCountArgs, "select">
  ): Promise<number> {
    return this.prisma.plagiarismAlgorithm.count(args);
  }

  async plagiarismAlgorithms(
    args: Prisma.PlagiarismAlgorithmFindManyArgs
  ): Promise<PrismaPlagiarismAlgorithm[]> {
    return this.prisma.plagiarismAlgorithm.findMany(args);
  }
  async plagiarismAlgorithm(
    args: Prisma.PlagiarismAlgorithmFindUniqueArgs
  ): Promise<PrismaPlagiarismAlgorithm | null> {
    return this.prisma.plagiarismAlgorithm.findUnique(args);
  }
  async createPlagiarismAlgorithm(
    args: Prisma.PlagiarismAlgorithmCreateArgs
  ): Promise<PrismaPlagiarismAlgorithm> {
    return this.prisma.plagiarismAlgorithm.create(args);
  }
  async updatePlagiarismAlgorithm(
    args: Prisma.PlagiarismAlgorithmUpdateArgs
  ): Promise<PrismaPlagiarismAlgorithm> {
    return this.prisma.plagiarismAlgorithm.update(args);
  }
  async deletePlagiarismAlgorithm(
    args: Prisma.PlagiarismAlgorithmDeleteArgs
  ): Promise<PrismaPlagiarismAlgorithm> {
    return this.prisma.plagiarismAlgorithm.delete(args);
  }
}
