/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Check } from "./Check";
import { CheckCountArgs } from "./CheckCountArgs";
import { CheckFindManyArgs } from "./CheckFindManyArgs";
import { CheckFindUniqueArgs } from "./CheckFindUniqueArgs";
import { DeleteCheckArgs } from "./DeleteCheckArgs";
import { CheckDto } from "../CheckDto";
import { CheckService } from "../check.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Check)
export class CheckResolverBase {
  constructor(
    protected readonly service: CheckService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Check",
    action: "read",
    possession: "any",
  })
  async _checksMeta(
    @graphql.Args() args: CheckCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Check])
  @nestAccessControl.UseRoles({
    resource: "Check",
    action: "read",
    possession: "any",
  })
  async checks(@graphql.Args() args: CheckFindManyArgs): Promise<Check[]> {
    return this.service.checks(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Check, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Check",
    action: "read",
    possession: "own",
  })
  async check(
    @graphql.Args() args: CheckFindUniqueArgs
  ): Promise<Check | null> {
    const result = await this.service.check(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Check)
  @nestAccessControl.UseRoles({
    resource: "Check",
    action: "delete",
    possession: "any",
  })
  async deleteCheck(
    @graphql.Args() args: DeleteCheckArgs
  ): Promise<Check | null> {
    try {
      return await this.service.deleteCheck(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CheckDto)
  async CreateCheck(
    @graphql.Args()
    args: CheckDto
  ): Promise<CheckDto> {
    return this.service.CreateCheck(args);
  }

  @graphql.Query(() => CheckDto)
  async GetCheck(
    @graphql.Args()
    args: string
  ): Promise<CheckDto> {
    return this.service.GetCheck(args);
  }
}
