/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PlagiarismDocument } from "./PlagiarismDocument";
import { PlagiarismDocumentCountArgs } from "./PlagiarismDocumentCountArgs";
import { PlagiarismDocumentFindManyArgs } from "./PlagiarismDocumentFindManyArgs";
import { PlagiarismDocumentFindUniqueArgs } from "./PlagiarismDocumentFindUniqueArgs";
import { DeletePlagiarismDocumentArgs } from "./DeletePlagiarismDocumentArgs";
import { PlagiarismDocumentService } from "../plagiarismDocument.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PlagiarismDocument)
export class PlagiarismDocumentResolverBase {
  constructor(
    protected readonly service: PlagiarismDocumentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PlagiarismDocument",
    action: "read",
    possession: "any",
  })
  async _plagiarismDocumentsMeta(
    @graphql.Args() args: PlagiarismDocumentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PlagiarismDocument])
  @nestAccessControl.UseRoles({
    resource: "PlagiarismDocument",
    action: "read",
    possession: "any",
  })
  async plagiarismDocuments(
    @graphql.Args() args: PlagiarismDocumentFindManyArgs
  ): Promise<PlagiarismDocument[]> {
    return this.service.plagiarismDocuments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PlagiarismDocument, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PlagiarismDocument",
    action: "read",
    possession: "own",
  })
  async plagiarismDocument(
    @graphql.Args() args: PlagiarismDocumentFindUniqueArgs
  ): Promise<PlagiarismDocument | null> {
    const result = await this.service.plagiarismDocument(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PlagiarismDocument)
  @nestAccessControl.UseRoles({
    resource: "PlagiarismDocument",
    action: "delete",
    possession: "any",
  })
  async deletePlagiarismDocument(
    @graphql.Args() args: DeletePlagiarismDocumentArgs
  ): Promise<PlagiarismDocument | null> {
    try {
      return await this.service.deletePlagiarismDocument(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
