/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AnalysisResult } from "./AnalysisResult";
import { AnalysisResultCountArgs } from "./AnalysisResultCountArgs";
import { AnalysisResultFindManyArgs } from "./AnalysisResultFindManyArgs";
import { AnalysisResultFindUniqueArgs } from "./AnalysisResultFindUniqueArgs";
import { CreateAnalysisResultArgs } from "./CreateAnalysisResultArgs";
import { UpdateAnalysisResultArgs } from "./UpdateAnalysisResultArgs";
import { DeleteAnalysisResultArgs } from "./DeleteAnalysisResultArgs";
import { SimilarityCheckFindManyArgs } from "../../similarityCheck/base/SimilarityCheckFindManyArgs";
import { SimilarityCheck } from "../../similarityCheck/base/SimilarityCheck";
import { Document } from "../../document/base/Document";
import { AnalysisResultService } from "../analysisResult.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AnalysisResult)
export class AnalysisResultResolverBase {
  constructor(
    protected readonly service: AnalysisResultService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AnalysisResult",
    action: "read",
    possession: "any",
  })
  async _analysisResultsMeta(
    @graphql.Args() args: AnalysisResultCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AnalysisResult])
  @nestAccessControl.UseRoles({
    resource: "AnalysisResult",
    action: "read",
    possession: "any",
  })
  async analysisResults(
    @graphql.Args() args: AnalysisResultFindManyArgs
  ): Promise<AnalysisResult[]> {
    return this.service.analysisResults(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AnalysisResult, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AnalysisResult",
    action: "read",
    possession: "own",
  })
  async analysisResult(
    @graphql.Args() args: AnalysisResultFindUniqueArgs
  ): Promise<AnalysisResult | null> {
    const result = await this.service.analysisResult(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AnalysisResult)
  @nestAccessControl.UseRoles({
    resource: "AnalysisResult",
    action: "create",
    possession: "any",
  })
  async createAnalysisResult(
    @graphql.Args() args: CreateAnalysisResultArgs
  ): Promise<AnalysisResult> {
    return await this.service.createAnalysisResult({
      ...args,
      data: {
        ...args.data,

        document: args.data.document
          ? {
              connect: args.data.document,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AnalysisResult)
  @nestAccessControl.UseRoles({
    resource: "AnalysisResult",
    action: "update",
    possession: "any",
  })
  async updateAnalysisResult(
    @graphql.Args() args: UpdateAnalysisResultArgs
  ): Promise<AnalysisResult | null> {
    try {
      return await this.service.updateAnalysisResult({
        ...args,
        data: {
          ...args.data,

          document: args.data.document
            ? {
                connect: args.data.document,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AnalysisResult)
  @nestAccessControl.UseRoles({
    resource: "AnalysisResult",
    action: "delete",
    possession: "any",
  })
  async deleteAnalysisResult(
    @graphql.Args() args: DeleteAnalysisResultArgs
  ): Promise<AnalysisResult | null> {
    try {
      return await this.service.deleteAnalysisResult(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SimilarityCheck], { name: "similarityChecks" })
  @nestAccessControl.UseRoles({
    resource: "SimilarityCheck",
    action: "read",
    possession: "any",
  })
  async findSimilarityChecks(
    @graphql.Parent() parent: AnalysisResult,
    @graphql.Args() args: SimilarityCheckFindManyArgs
  ): Promise<SimilarityCheck[]> {
    const results = await this.service.findSimilarityChecks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Document, {
    nullable: true,
    name: "document",
  })
  @nestAccessControl.UseRoles({
    resource: "Document",
    action: "read",
    possession: "any",
  })
  async getDocument(
    @graphql.Parent() parent: AnalysisResult
  ): Promise<Document | null> {
    const result = await this.service.getDocument(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
