/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PlagiarismUser } from "./PlagiarismUser";
import { PlagiarismUserCountArgs } from "./PlagiarismUserCountArgs";
import { PlagiarismUserFindManyArgs } from "./PlagiarismUserFindManyArgs";
import { PlagiarismUserFindUniqueArgs } from "./PlagiarismUserFindUniqueArgs";
import { DeletePlagiarismUserArgs } from "./DeletePlagiarismUserArgs";
import { PlagiarismUserService } from "../plagiarismUser.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PlagiarismUser)
export class PlagiarismUserResolverBase {
  constructor(
    protected readonly service: PlagiarismUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PlagiarismUser",
    action: "read",
    possession: "any",
  })
  async _plagiarismUsersMeta(
    @graphql.Args() args: PlagiarismUserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PlagiarismUser])
  @nestAccessControl.UseRoles({
    resource: "PlagiarismUser",
    action: "read",
    possession: "any",
  })
  async plagiarismUsers(
    @graphql.Args() args: PlagiarismUserFindManyArgs
  ): Promise<PlagiarismUser[]> {
    return this.service.plagiarismUsers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PlagiarismUser, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PlagiarismUser",
    action: "read",
    possession: "own",
  })
  async plagiarismUser(
    @graphql.Args() args: PlagiarismUserFindUniqueArgs
  ): Promise<PlagiarismUser | null> {
    const result = await this.service.plagiarismUser(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PlagiarismUser)
  @nestAccessControl.UseRoles({
    resource: "PlagiarismUser",
    action: "delete",
    possession: "any",
  })
  async deletePlagiarismUser(
    @graphql.Args() args: DeletePlagiarismUserArgs
  ): Promise<PlagiarismUser | null> {
    try {
      return await this.service.deletePlagiarismUser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
