/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Algorithm } from "./Algorithm";
import { AlgorithmCountArgs } from "./AlgorithmCountArgs";
import { AlgorithmFindManyArgs } from "./AlgorithmFindManyArgs";
import { AlgorithmFindUniqueArgs } from "./AlgorithmFindUniqueArgs";
import { CreateAlgorithmArgs } from "./CreateAlgorithmArgs";
import { UpdateAlgorithmArgs } from "./UpdateAlgorithmArgs";
import { DeleteAlgorithmArgs } from "./DeleteAlgorithmArgs";
import { AlgorithmService } from "../algorithm.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Algorithm)
export class AlgorithmResolverBase {
  constructor(
    protected readonly service: AlgorithmService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Algorithm",
    action: "read",
    possession: "any",
  })
  async _algorithmsMeta(
    @graphql.Args() args: AlgorithmCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Algorithm])
  @nestAccessControl.UseRoles({
    resource: "Algorithm",
    action: "read",
    possession: "any",
  })
  async algorithms(
    @graphql.Args() args: AlgorithmFindManyArgs
  ): Promise<Algorithm[]> {
    return this.service.algorithms(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Algorithm, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Algorithm",
    action: "read",
    possession: "own",
  })
  async algorithm(
    @graphql.Args() args: AlgorithmFindUniqueArgs
  ): Promise<Algorithm | null> {
    const result = await this.service.algorithm(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Algorithm)
  @nestAccessControl.UseRoles({
    resource: "Algorithm",
    action: "create",
    possession: "any",
  })
  async createAlgorithm(
    @graphql.Args() args: CreateAlgorithmArgs
  ): Promise<Algorithm> {
    return await this.service.createAlgorithm({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Algorithm)
  @nestAccessControl.UseRoles({
    resource: "Algorithm",
    action: "update",
    possession: "any",
  })
  async updateAlgorithm(
    @graphql.Args() args: UpdateAlgorithmArgs
  ): Promise<Algorithm | null> {
    try {
      return await this.service.updateAlgorithm({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Algorithm)
  @nestAccessControl.UseRoles({
    resource: "Algorithm",
    action: "delete",
    possession: "any",
  })
  async deleteAlgorithm(
    @graphql.Args() args: DeleteAlgorithmArgs
  ): Promise<Algorithm | null> {
    try {
      return await this.service.deleteAlgorithm(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
