/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { SimilarityCheckUpdateManyWithoutDocumentsInput } from "./SimilarityCheckUpdateManyWithoutDocumentsInput";
import { Type } from "class-transformer";
import { AnalysisResultUpdateManyWithoutDocumentsInput } from "./AnalysisResultUpdateManyWithoutDocumentsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class DocumentUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  author?: string | null;

  @ApiProperty({
    required: false,
    type: () => SimilarityCheckUpdateManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => SimilarityCheckUpdateManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => SimilarityCheckUpdateManyWithoutDocumentsInput, {
    nullable: true,
  })
  similarityChecks?: SimilarityCheckUpdateManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => AnalysisResultUpdateManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => AnalysisResultUpdateManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => AnalysisResultUpdateManyWithoutDocumentsInput, {
    nullable: true,
  })
  analysisResults?: AnalysisResultUpdateManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  documentContent?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  documentTitle?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  documentAuthor?: string | null;
}

export { DocumentUpdateInput as DocumentUpdateInput };
