/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { SimilarityCheckCreateNestedManyWithoutDocumentsInput } from "./SimilarityCheckCreateNestedManyWithoutDocumentsInput";
import { Type } from "class-transformer";
import { AnalysisResultCreateNestedManyWithoutDocumentsInput } from "./AnalysisResultCreateNestedManyWithoutDocumentsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class DocumentCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  author?: string | null;

  @ApiProperty({
    required: false,
    type: () => SimilarityCheckCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => SimilarityCheckCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => SimilarityCheckCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  similarityChecks?: SimilarityCheckCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => AnalysisResultCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => AnalysisResultCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => AnalysisResultCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  analysisResults?: AnalysisResultCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  documentContent?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  documentTitle?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  documentAuthor?: string | null;
}

export { DocumentCreateInput as DocumentCreateInput };
